app/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('',views.home,name='home'),
    path('readblog/<int:id>',views.readblog,name='read'),
    path('sign',views.sign_up,name='sign'),
    path('login/',views.loginuser,name='log'),
    path('profile/',views.userprofile,name='pro'),
    path('logout',views.logoutuser,name='out'),
    path('addpost',views.add_post,name='add'),
    path('contactpage',views.contact,name='con'),
    path('update/<int:id>',views.edit_post,name='edit'),
    path('delete/<int:id>',views.delete_post,name='delete'),
    path('password/',views.changepass,name='changepass'),
    path('aboutpage',views.about,name='about'),
    path('search',views.search,name='search'),
    path('category/<str:cats>',views.category,name='category'),
    # path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    # path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('',include('django.contrib.auth.urls')),
    path('readblog/postComment', views.postComment, name="postComment"),
    path('editprofile',views.EditProfile.as_view(), name="editpro"),
    
    # path('profile/<int:pk>',views.Usershowprofile.as_view(), name="userpro"),

]

minor/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

class category(models.Model):
    name=models.CharField(max_length=50)

    def __str__(self):
        return   str(self.name)




class blog(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return   str(self.id)  + ' | ' +  self.title + ' | ' + str(self.author)
         
    title = models.CharField(max_length=250)
    desc = models.CharField(max_length=300)
    photo = models.ImageField(upload_to="postimages")
    head0 = models.CharField(max_length=400)
    shead0 = RichTextField(blank=True,null=True)
    post_date = models.DateField(auto_now_add=True)
    category = models.CharField(max_length=50)


   
    
class contact(models.Model):
    name = models.CharField(max_length=150)
    email= models.EmailField(max_length=254) 
    desc = models.CharField(max_length=400)

    def __str__(self):
        return  str (self.desc)

class BlogComment(models.Model):
    sno= models.AutoField(primary_key=True)
    comment=models.TextField()
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    post=models.ForeignKey(blog, on_delete=models.CASCADE)
    parent=models.ForeignKey('self',on_delete=models.CASCADE, null=True )
    post_date = models.DateField(auto_now_add=True)
    

    def __str__(self):
        return self.comment[0:13] + "..." + "by" + " " + self.user.username




  

app/forms.py
from .models import contact,blog,category
from django.contrib.auth import forms
from django.contrib.auth.forms import UserCreationForm ,UserChangeForm
from django.contrib.auth.models import User
from django import forms



class signupform(UserCreationForm):
     class Meta:
        model=User
        fields =['username','first_name','last_name','email','password1','password2']
        labels={'email': 'Email','password1': 'Password', 'password2': 'Confirm Password'}
    
choices= category.objects.all().values_list('name','name')

choices_list=[]

for item in choices:
    choices_list.append(item)



class Blogform(forms.ModelForm):
    class Meta:
        model=blog
        fields=[ 'author','title','desc','photo','head0','shead0','author','category']
        labels={ 'author':'Author','title':'Title', 'desc':'Description','head0':'Sub-title','shead0':'Sub-description' ,'photo':'Images','category':'Category'}
        widgets={'desc':forms.Textarea(),'shead0':forms.Textarea(),'category':forms.Select(choices=choices)}

class contactform(forms.ModelForm):
    class Meta:
        model=contact
        fields=['name','email','desc']
        labels={'name':'Name', 'email':'Email','desc':'Message'}
        widgets={
            'name':forms.TextInput(attrs={'class':'input','placeholder':'Your Name', 'label_suffix' :'- '}),
            'email':forms.EmailInput(attrs={'class':'input','placeholder':'you@gmail.com'}),
            'desc':forms.Textarea(attrs={'class':'textarea','rows':6,'placeholder':'Your message'})    
        }
    

class EditUserform(UserChangeForm):

    email= forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control',}))
    first_name =forms.CharField(max_length=100 ,widget=forms.TextInput (attrs={'class':'form-control'}))
    last_name =forms.CharField(max_length=100 ,widget=forms.TextInput (attrs={'class':'form-control'}))
    username =forms.CharField(max_length=100 ,widget=forms.TextInput (attrs={'class':'form-control'}))

    class Meta:
        model=User
        fields =['username','first_name','last_name','email','password' ]
        labels={'email': 'Email','password': 'Password', 'username':'Username','first_name':'First Name'}

app/templates/Edit_profile.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %} 
{% load static %}
{%block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'css/add.css' %}" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<linkhref="https://fonts.googleapis.com/css2?family=Archivo+Narrow&display=swap" rel="stylesheet"/>

{% endblock head %} {% block body %}
<body
  background="{% static 'images/ist.jpg' %}"
  style="
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: 100% 100%;
  "
>
  {% include 'navbar.html' %} 
  {% if messages %} 
  {% for message in messages %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endfor %} {% endif %}

  <div class="container h-100">
    <div class="d-flex justify-content-center h-100">
      <div class="user_card" style="width:950px">
        <div class="d-flex justify-content-center">
          <h3 id="form-title" style="font-size: 2.75rem">Edit Profile</h3>
        </div>
        <div class="d-flex justify-content-center form_container" style="color: #106186">
          <form method="POST" action="" enctype="multipart/form-data" style="width: 60vw">
            {% csrf_token %} 
            {{form|crispy}}
            <br>
            <button class="btn btn-lg" style=" color: #fff9f9; background-color: #106186;border-color: #106186; ">Update Profile</button>
          </form>
        </div>
      </div>
    </div>
    
    {% endblock body %}
  </div>
</body>

app/templates/Userprofile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>User Profile</h1>
    <div class="col-md-2 ">
        <img class="rounded mx-auto d-block w-100" src= alt="user">
      </div>
</body>
</html>

app/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href={% static 'css/about.css' %}>
{% endblock head %}


{% comment %} BODY PART {% endcomment %}
{% block body %}
{% include 'navbar.html' %}
{% comment %} <div class="container">
    <video autoplay loop muted>
        <source src="{% static 'videos/Pexels.mp4' %}" type="video/mp4">
    </video>
</div>
<div class="text-box">
    <h1 style="font-size: 10.5rem;">Bloggle</h1>
</div> {% endcomment %}
<div class="container" style="height: 85vh; width: 116vh; margin: 5vh 0vh -25vh 10vh; display:inline;">
<img src={% static 'images/webdev.png' %} alt="" style="height: 75vh;">
</div>
<div class="conatiner2" style="width: 30vw; margin: -14vw 0vw 0vw 57vw; display: inline-block;">
<h2 style="font-style: italic;color: red;font-size: 10vh; isolation: isolate;">About</h2>
<p style='font-size: 125%;'>This platform from where the users can connects and share their information or thoughts with others.
</p>
</div>


{% endblock body %}

app/templates/add.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% load static %}
{%block head %}
{% comment %} <link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
  crossorigin="anonymous"
/> {% endcomment %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<link rel="stylesheet" href="{% static 'css/add.css' %}" />

<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Archivo+Narrow&display=swap"
  rel="stylesheet"
/>

{% endblock head %} {% block body %}
<body
  background="{% static 'images/ist.jpg' %}"
  style="
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: 100% 100%;
  "
>
  {% include 'navbar.html' %} {% if messages %} {% for message in messages %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    {{message}}
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    ></button>
  </div>
  {% endfor %} {% endif %}

  <div class="container h-100">
    <div class="d-flex justify-content-center h-100">
      <div class="user_card" style="width:950px">
        <div class="d-flex justify-content-center">
          <h3 id="form-title" style="font-size: 2.75rem">Add post</h3>
        </div>
        <div
          class="d-flex justify-content-center form_container"
          style="color: #106186"
        >
          <form
            method="POST"
            action=""
            enctype="multipart/form-data"
            style="width: 60vw"
          >
            {% csrf_token %} {{form.media}} {{form|crispy}}

            <br />

            <input type="submit" value="Add" class="btn btn-lg" style="color: #fff9f9; background-color: #106186;border-color: #106186;"/>
            <a href='{% url 'pro' %}'class='btn btn-lg btn-secondary'>Back</a>

            
          </form>
        </div>
      </div>
    </div>

    {% endblock body %}
  </div>
</body>

app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    
    <title >Bloggle</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel=" icon" href="{% static 'images/favicon.png' %}" type="image/jpeg">
    
    

    {% block head %}
    {% endblock head %}
</head>
<body>

{% block body %}

{% endblock body %}
<script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.7/lib/darkmode-js.min.js"></script>
{% comment %} <script src="{% static 'js/new.js' %}"></script> {% endcomment %}
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script> 
{% comment %} <script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.7/lib/darkmode-js.min.js"></script> {% endcomment %}

</body>
</html>

app/templates/blogcontinue.html
{% extends 'base.html' %}
{% load static %}

{% load extras %}

{% block head %}

<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v12.0" nonce="WeWeMNAr"></script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Archivo+Narrow&family=Caveat:wght@400;700&family=Gloria+Hallelujah&family=Handlee&family=Patrick+Hand&display=swap" rel="stylesheet">

{% endblock head %}


{% block body %}

<body background="{% static 'images/ist.jpg' %}" style="background-repeat: no-repeat;background-attachment: fixed;background-size: 100% 100%;">
</body>

{% include "navbar.html" %}
{% comment %} <a href={% url 'userpro' post.author.profile.id %}>Profile</a> {% endcomment %}

<div class="container">
  <div class="row g-5">
    <div class="col-md-8" style="background: #fffaf0bf">
      <br>
      <div class="row featurette">
        <div class="col-md-7">
          <strong class="d-inline-block mb-2 text-primary"><p class="blog-post-meta"><a href="{% url 'category' post.category %}">{{post.category}}</a></p></strong>
          <h2 class="featurette-heading">{{post.title}} </h2>
          <p class="blog-post-meta">{{post.post_date}} by <a href="#">{{post.author}}</a></p>
          <p class="lead">{{post.desc}}</p>
          <h3 class="featurette-heading">{{post.head0}} </h3>
          <p class="lead">{{post.shead0|safe}}</p>

{% comment %} try {% endcomment %}
          {% comment %} <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
              <div class="col-md-4">
              
                <img src="{{post.author.image.url}}" class="img-fluid rounded-start" alt="...">
             

              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">{{post.author.username}}</h5>
                  <p class="card-text">{{post.author.pro}}</p>
                  <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                </div>
              </div>
            </div>
          </div>  {% endcomment %}

          <br>
          {% comment %} COMMENT {% endcomment %}
          
          <div class="container md-3">
            <h2> Comments ({{comments.count}})</h2>
            {% if user.is_authenticated %}
            <form action="/readblog/postComment" method="post">
              {% csrf_token %}
              <div class="form-group">
                <label for="exampleInputEmail1">Post Comment </label>
                <input type="text" class="form-control" name="comment" placeholder="Enter comment here">
              </div>
              <input type="hidden" name="postId" value="{{post.id}}">
              <input type="hidden" name="parentSno" value="">

              <button type="submit" class="btn btn-primary my-2">Submit</button>
            </form>
             {% else %}
               <h4> Please login for Comment a Post</h4>
             {% endif %}


             {% for comment in comments %}
                <div class="row my-3">
                  <div class="col-md-2  ">
                    {% comment %} <img class="rounded mx-auto d-block w-100" src={% static 'images/userimage.png' %} alt="user"> {% endcomment %}
                    <img class="rounded mx-auto d-block w-100" src={% static 'images/userimage.png' %} alt="user">
                  </div>
                  <div class="col-md-10 "> 
                    <b> {{comment.user.username}} </b> at {{comment.post_date}}
                    <div>   {{comment.comment}} </div> 

                    {% comment %} REPLY {% endcomment %}

                    {% if user.is_authenticated %}
                    <div class="reply my-2">
                      <button class="btn btn-sm btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#replyBox{{comment.sno}}" aria-expanded="false" aria-controls="replyBox{{comment.sno}}">Reply</button>
                      <div class="collapse my-2" id="replyBox{{comment.sno}}">
                        <div class="card card-body">
                          <form action="/readblog/postComment" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                              <label for="comment">Post a Reply </label>
                              <input type="text" class="form-control" name="comment" placeholder="Enter reply here">
                              <input type="hidden" name="parentSno" value="{{comment.sno}}">
                            </div>
                            <input type="hidden" name="postId" value="{{post.id}}">
                            <button type="submit" class="btn btn-primary my-2">Submit</button>
                          </form>
                        </div>
                      </div>
                    </div>
                    {% endif %}

                    <div class="replies ">
                      {% for reply in replyDict|get_val:comment.sno  %}
                      <div class="row my-3">
                        <div class="col-md-2 ">
                          <img class="rounded mx-auto d-block w-100" src={% static 'images/userimage.png' %} alt="user">
                        </div>
                        <div class="col-md-10">
                          <div class="col-md-10 ">
                            <b> {{reply.user.username}} </b> at {{reply.post_date}}
                            <div>{{reply.comment}}</div>
                          </div>
                          
                        </div>
                      </div>
                      {% endfor %}
                    </div>
                    
                   
                  </div>
                </div>
             {% endfor %}
          </div>
        </div>
        
        <div class="col-md-5">
          <img src="{{post.photo.url}}" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto"  alt="" width="600" height="400" aria-label="Placeholder: 600x400" preserveAspectRatio="xMidYMid slice" focusable="false"  ><rect width="100%" height="100%" fill="#eee"></rect>
        </div>
      </div>
    </div>

    <div class="col-md-4">
     <br>
      <div class="position-sticky" style="top: 2rem;">
        <div class="p-4 mb-3 bg-light rounded">
      
          <h4 class="fst-italic">About</h4>
          <p class="mb-0">Customize this section to tell your visitors a little bit about your publication, writers, content, or something else entirely. Totally up to you.</p>
        </div>

        <div class="p-4" style="background-color: #f8f9fa;">
          <h4 class="fst-italic" style='color: crimson; isolation: isolate;'>Archives</h4>
          <ol class="list-unstyled mb-0">
            <li><a class="ex2" href="#">November 2021</a></li>
            <li><a class="ex2" href="#">October 2021</a></li>
            <li><a class="ex2" href="#">September 2021</a></li>
            <li><a class="ex2" href="#">August 2021</a></li>
            <li><a class="ex2" href="#">July 2021</a></li>
            <li><a class="ex2" href="#">June 2021</a></li>
            <li><a class="ex2" href="#">May 2021</a></li>
            <li><a class="ex2" href="#">April 2021</a></li>
            <li><a class="ex2" href="#">March 2021</a></li>
            <li><a class="ex2" href="#">February 2021</a></li>
            <li><a class="ex2" href="#">January 2021</a></li>
            <li><a class="ex2" href="#">December 2020</a></li>
          </ol>
        </div>

        <div class="p-4" style="background-color: #f8f9fa;">
          <h4 class="fst-italic" style='color: crimson; isolation: isolate;'>Elsewhere</h4>
          <ol class="list-unstyled">
            <li><a class="ex2"> GitHub</a></li>
            <li><a class="ex2" href="#">Twitter</a></li>
            <li><a class="ex2" href="#">Facebook</a></li>
          </ol>
        </div>
      </div>
    </div>
  </div>

</div>
{% endblock body %}

app/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block head %}

 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<link rel="stylesheet" href="{% static 'css/contact.css' %}">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Archivo+Narrow&display=swap" rel="stylesheet">




{% endblock head %}

{% block body  %}



{% include 'navbar.html' %}
{% if messages %}
  {% for message in messages  %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{message}} 
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
   {% endfor %}
{% endif %}
	 <body background="{% static 'images/ist.jpg' %}" style="background-repeat: no-repeat;background-attachment: fixed;background-size: 100% 100%;">
	<div class="container h-100" >
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
                    <h3 id="form-title" style="font-size: 2.75rem;">Contact</h3>
				</div>
				<div class="d-flex justify-content-center form_container" style="color: #106186;">
				<form method="POST" action="" novalidate>
			
						{% csrf_token %}
				<div id="div_id_name" class="form-group" style="font-family: 'Archivo Narrow', sans-serif; font-size: 125%;margin: 0px 0px 20px 0px;"> 
				<label for="id_name" class=" requiredField">Name </label> 
				<div class=""> <input type="text" name="name" class="input textinput textInput form-control" placeholder="Your Name" label_suffix="- " maxlength="150" required="" id="id_name"> </div> </div>

                <div id="div_id_email" class="form-group" style="font-family: 'Archivo Narrow', sans-serif; font-size: 125%; margin: 0px 0px 20px 0px;"> 
	            <label for="id_email" class=" requiredField"> Email </label> 
	            <div class=""> <input type="email" name="email" class="input emailinput form-control" placeholder="you@gmail.com" maxlength="254" required="" id="id_email"> </div> </div>


                <div id="div_id_desc" class="form-group" style="font-family: 'Archivo Narrow', sans-serif; font-size: 125%; margin: 0px 0px 20px 0px;"> 
	            <label for="id_desc" class=" requiredField">Message </label> 
	           <div class=""> <textarea name="desc" cols="40" rows="6" class="textarea form-control" placeholder="Your message" maxlength="400" required="" id="id_desc"></textarea> </div> </div>

			   {{form.errors}}
                        
                <input type="submit" value="Send" class="btn btn-lg" style=" color: #fff9f9; background-color: #106186;border-color: #106186; ">
    
					</form>

				</div>

	
				
			</div>
		</div>
{% endblock body %}

app/templates/signup.html
{% extends 'base.html' %}
{% load static %}


{% block head %}

{% include 'navbar.html' %}
<title>Login</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous"> 
<link rel="stylesheet" href="{% static 'css/sign.css' %}"> 
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Archivo+Narrow&display=swap" rel="stylesheet">

{% endblock head %}
	

{% block body %}
<body background="{% static 'images/ist.jpg' %}" style="background-repeat: no-repeat;background-attachment: fixed;background-size: 100% 100%;">

{% if messages %}
  {% for message in messages  %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{message}} 
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
   {% endfor %}
{% endif %}




<div class="container h-100">
	<div class="d-flex justify-content-center h-100">
		<div class="user_card">
			<div class="d-flex justify-content-center" >
					<h3 id="form-title" style="font-size: 2.75rem;">SIGNUP</h3>
			</div>
			   <div class="d-flex justify-content-center form_container">
                    <form method="POST" action="" novalidate style=" height: 70vh; width: 50vh;">
						  
						
                        <div id="div_id_username" class="form-group" style="font-family: 'Archivo Narrow', sans-serif; font-size: 125%; margin: 0px 0px 20px 0px;"> 
				            <label for="id_username" class=" requiredField" >Username</label> 
				            <div class=""> 
				             <input type="text" name="username" placeholder="" maxlength="150" autofocus="" class="textinput textInput form-control" required="" id="id_username"> 
				            </div> 
			            </div>

                        <div id="div_id_email" class="form-group" style="font-family: 'Archivo Narrow', sans-serif; font-size: 125%; margin: 0px 0px 20px 0px;"> 
				           <label for="id_email" class=" requiredField">Email</label> 
				            <div class=""> 
						    <input type="email" name="email" class="input emailinput form-control"  maxlength="254" required="" id="id_email"> 
						    </div> 
				         </div>

                        <div id="div_id_password1" class="form-group" style="font-family: 'Archivo Narrow', sans-serif; font-size:125%; margin: 0px 0px 20px 0px;"> 
					        <label for="id_password1" class=" requiredField" style= "color: #000;">Password </label>
					        <div class=""> 
						      <input type="password" name="password1" autocomplete="new-password" class="textinput textInput form-control" required="" id="id_password1">  
						    </div> 
				        </div>

                        <div id="div_id_password2" class="form-group" style="font-family: 'Archivo Narrow', sans-serif; font-size: 125%; margin: 0px 0px 20px 0px;"> 
				          <label for="id_password2" class=" requiredField" style= "color:#000;">Password confirmation </label> 
					        <div class=""> 
						      <input type="password" name="password2" autocomplete="new-password" class="textinput textInput form-control" required="" id="id_password2">  
					        </div> 
				        </div> 
						
					 
				
                        {% csrf_token %}
                        <input type="submit" value="Submit" class="btn btn-lg" style=" color: #fff9f9; background-color: #106186;border-color: #106186; ">
					      
						
						  
						
			        </form>
                </div>	
				<p>{{form.errors}}</p> 
	    </div>			
	</div>
</div>

			     

{% endblock body %}